print ("My name is Binay Shrestha, and I am from Lalitpur, Nepal.")
print("I am currently learning Python to enhance my skills in automation.")
print("I have prior basic experience with HTML and Apps Script.")
print("I love coding and enjoy building tools and systems that simplify workflows.")
print("I work with tools like Google Sheets, Apps Script, and HTML/CSS for web apps and data management.")
print("Python will be a valuable addition to my skill set and beneficial for my future career.")
print("This is my first online IT course, and I’m excited to explore its possibilities.")
print("I am committed to continuous learning and staying updated with the latest technologies.")
print("I aim to integrate Python with my existing skills to create more advanced systems and workflows.")
print("Thank you")